# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ricric

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ricacrdemo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_584399608e894a81b4b3469da68bee32 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3249ec2d4f5e4742af5a14ebbf28483c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ricacrdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_584399608e894a81b4b3469da68bee32 }}/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ricric'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a8422082d4924987992000aa4b15d84d }}
        images: 'ricacrdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_584399608e894a81b4b3469da68bee32 }}/webimage:${{ github.sha }}'